name: Week 5
on:
  push:
    branches:
      - week5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 1
        if: ${{steps.vars.outputs.count == 33 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/test.5.1.js

      - name: Step 4
        if: ${{steps.vars.outputs.count == 36 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/test.5.4.js

