title: Sample Learning Lab
description: >-
    Course description: Place your course description here...
template:
    name: learninglab-template
    repo: your-learninglab-template
before:
    - type: createIssue
      title: Week 1
      body: 1.1-Week 1 Step 1.md
steps:
    - title: 'Week 1: GitHub'
      description: '✅  Tasks:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: respond
          with: 1.2-Week 1 Step 2.md
          files: ['blog.md']
          scripts: n/a
    - title: 'Week 1: Say "Hello" to VS Code'
      description: '✅  Tasks:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 1.3-Week 1 Step 3.md
          files: ['n/a']
          scripts: test.1.2.js
    - title: 'Week 1: Getting Cat Pics with Postman 🐱'
      description: '✅  Tasks:'
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: 1.4-Week 1 Step 4.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 1: Building our first function ⚡[HackerVoice]'
      description: '✅  Tasks:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 1.5-Week 1 Step 5.md
          files: ['n/a']
          scripts: test.1.4.js
    - title: 'Week 1: Let me in!'
      description: '✅ Tasks:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 1.6-Week 1 Step 6.md
          files: ['n/a']
          scripts: test.1.5.js
    - title: 'Week 1: Trying to make node-fetch happen'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 1.7-Week 1 Step 7.md
          files: ['n/a']
          scripts: test.1.6.js
    - title: 'Week 1: Name your Cat'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 1.8-Week 1 Step 8.md
          files: ['n/a']
          scripts: test.1.7.js
    - title: 'Week 1: [TOP SECRET] Morse Code Converter'
      description: '✅  Tasks:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 1.9-Week 1 Step 9.md
          files: ['n/a']
          scripts: test.1.8.js
    - title: 'Week 1: 📝 Week 1 Livestream Feedback'
      description: '📝 Week 1 Livestream Feedback'
      event: issue_comment.created
      stepType: feedback
      actions:
        - type: respond
          with: feedback.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 1: Feedback'
      description: Provide your feedback for Week 1!
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: 1-complete.md
        - type: createIssue
          title: Week 2
          body: 2.1-Week 2 Step 1.md
        - type: closeIssue
    - title: 'Week 2: Getting Emotional ~ With the Face API'
      description: '✅ Task:'
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: 2.2-Week 2 Step 2.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 2: Getting Emotional ~ With Parse-Multipart'
      description: '✅ Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 2.3-Week 2 Step 3.md
          files: ['n/a']
          scripts: test.2.2.js
    - title: 'Week 2: Getting Emotional ~ With the Face API'
      description: '✅ Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 2.4-Week 2 Step 4.md
          files: ['n/a']
          scripts: test.2.3.js
    - title: 'Week 2: Getting Emotional ~ Returning the Dominant Emotion'
      description: '✅ Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 2.5-Week 2 Step 5.md
          files: ['n/a']
          scripts: test.2.4.js
    - title: 'Week 2: Getting Emotional ~ Calling the Giphy API'
      description: '✅ Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 2.6-Week 2 Step 6.md
          files: ['n/a']
          scripts: test.2.5.js
    - title: 'Week 2: Pose! Song Recommendation with Age Recognition'
      description: '✅ Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 2.7-Week 2 Step 7.md
          files: ['n/a']
          scripts: test.2.6.js
    - title: 'Week 2: How old are you??'
      description: '✅ Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 2.8-Week 2 Step 8.md
          files: ['n/a']
          scripts: test.2.7.js
    - title: 'Week 2: Ok, Boomer :neutral_face:'
      description: '✅ Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 2.9-Week 2 Step 9.md
          files: ['n/a']
          scripts: test.2.8.js
    - title: 'Week 2: 📝 Week 2 Livestream Feedback'
      description: '📝 Week 2 Livestream Feedback'
      event: issue_comment.created
      stepType: feedback
      actions:
        - type: respond
          with: feedback.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 2: Feedback'
      description: Provide your feedback for Week 2!
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: 2-complete.md
        - type: createIssue
          title: Week 3
          body: 3.1-Week 3 Step 1.md
        - type: closeIssue
    - title: 'Week 3: Blob Storage & Me'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 3.2-Week 3 Step 2.md
          files: ['n/a']
          scripts: test.3.1.js
    - title: 'Week 3: Upload it!'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 3.3-Week 3 Step 3.md
          files: ['n/a']
          scripts: test.3.2.js
    - title: 'Week 3: Codename Blob + 3RR0R Handling'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 3.4-Week 3 Step 4.md
          files: ['n/a']
          scripts: test.3.3.js
    - title: 'Week 3: Your time's up....'
      description: '✅  Task:'
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: 3.5-Week 3 Step 5.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 3: Download it!'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 3.6-Week 3 Step 6.md
          files: ['n/a']
          scripts: test.3.5.js
    - title: 'Week 3: Can you keep a secret?'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 3.7-Week 3 Step 7.md
          files: ['n/a']
          scripts: test.3.6.js
    - title: 'Week 3: Leaky secrets'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 3.8-Week 3 Step 8.md
          files: ['n/a']
          scripts: test.3.7.js
    - title: 'Week 3: Exposed!!'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 3.9-Week 3 Step 9.md
          files: ['n/a']
          scripts: test.3.8.js
    - title: 'Week 3: 📝 Week 3 Livestream Feedback'
      description: '📝 Week 3 Livestream Feedback'
      event: issue_comment.created
      stepType: feedback
      actions:
        - type: respond
          with: feedback.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 3: Feedback'
      description: Provide your feedback for Week 3!
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: 3-complete.md
        - type: createIssue
          title: Week 4
          body: 4.1-Week 4 Step 1.md
        - type: closeIssue
    - title: 'Week 4: Adding an Event Handler to your HTML Form!'
      description: 'Demo: [🐰](https://week4step1.emilychen10.repl.co/)'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 4.2-Week 4 Step 2.md
          files: ['n/a']
          scripts: 4.1.spec.js
    - title: 'Week 4: Error Handling ~ Sir this is a Wendy's'
      description: 'Demo: [🐰](https://week4step2.emilychen10.repl.co)'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 4.3-Week 4 Step 3.md
          files: ['n/a']
          scripts: 4.2.spec.js
    - title: 'Week 4: Making `fetch` Happen'
      description: 'Demo: [🐰](https://week4step3.emilychen10.repl.co)'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 4.4-Week 4 Step 4.md
          files: ['n/a']
          scripts: 4.3.spec.js
    - title: 'Week 4: Downloading your image!'
      description: 'Demo: [🐰](https://week4step4.emilychen10.repl.co/)'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 4.5-Week 4 Step 5.md
          files: ['n/a']
          scripts: 4.4.spec.js
    - title: 'Week 4: Create the CataaS Website ~ meow'
      description: 'Demo: [🐱](https://week4step5.emilychen10.repl.co/)'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 4.6-Week 4 Step 6.md
          files: ['n/a']
          scripts: 4.5.spec.js
    - title: 'Week 4: One Cat isn't enough ~ Meow'
      description: '✅  Task:'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 4.7-Week 4 Step 7.md
          files: ['n/a']
          scripts: 4.6.spec.js
    - title: 'Week 4: Ultimate CAT INVASION! ~'
      description: 'Demo: [🐱](https://week4step7.emilychen10.repl.co/)'
      event: workflow_run.completed
      stepType: checks
      actions:
        - type: respond
          with: 4.8-Week 4 Step 8.md
          files: ['n/a']
          scripts: 4.7.spec.js
    - title: 'Week 4: 📝 Week 4 Livestream Feedback'
      description: '📝 Week 4 Livestream Feedback'
      event: issue_comment.created
      stepType: feedback
      actions:
        - type: respond
          with: feedback.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 4: Feedback'
      description: Provide your feedback for Week 4!
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: 4-complete.md
        - type: createIssue
          title: Starting your Final Project
          body: 5.1-Week 5 Step 1.md
        - type: closeIssue
    - title: 'Week 5: Laying out the groundwork'
      description: '✅  Task:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: createIssue
          title: Laying out the groundwork
          body: 5.2-Week 5 Step 2.md
        - type: closeIssue
    - title: 'Week 5: Laying out the groundwork'
      description: '✅  Task:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: createIssue
          title: Reviewing your Flowchart
          body: 5.3-Week 5 Step 3.md
        - type: closeIssue
    - title: 'Week 5: Reviewing your Flowchart'
      description: '✅  Task:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: createIssue
          title: Timeline
          body: 5.4-Week 5 Step 4.md
        - type: closeIssue
    - title: 'Week 5: Timeline'
      description: '✅  Task:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: createIssue
          title: Start Coding!
          body: 5.5-Week 5 Step 5.md
        - type: closeIssue
    - title: 'Week 5: Start Coding!'
      description: '✅  Task:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: createIssue
          title: Documentation
          body: 5.6-Week 5 Step 6.md
        - type: closeIssue
    - title: 'Week 5: Documentation'
      description: '✅  Task:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: createIssue
          title: Continuing your work
          body: 5.7-Week 5 Step 7.md
        - type: closeIssue
    - title: 'Week 5: Laying out the groundwork'
      description: '✅  Task:'
      event: pull_request.closed
      stepType: PRmerge
      actions:
        - type: respond
          with: feedback.md
          files: ['n/a']
          scripts: n/a
    - title: 'Week 5: Feedback'
      description: Provide your feedback for Week 5!
      event: issue_comment.created
      stepType: IssueComment
      actions:
        - type: respond
          with: finalproject.md
        - type: closeIssue
